exclude = [
  "@ref",
  "@cite",
  "^https://github.com/.*/releases/tag/v.*$",
  "^https://doi.org/FIXME$",
  "^https://alejandromerchan.github.io/USDAQuickStats.jl/stable$",
  "zenodo.org/badge/DOI/FIXME$",
  "^https://quickstats.nass.usda.gov"
]

exclude_path = [
  "docs/build"
]
