name = "USDAQuickStats"
uuid = "7a997779-2268-4af1-92a2-957a4c5037ec"
authors = ["H. Alejandro Merchan", "California Department of Pesticide Regulation"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[compat]
HTTP = "0.8"
julia = "1"
JSON3 = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
